/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbs;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Null
 */
public class vsComputer extends javax.swing.JFrame {
        String player1moveList[] = new String[4];
        String player2moveList[] = new String[4];
        int player1Info[] = new int[4];
        int player2Info[] = new int[3];
        int player1moveDamage[] = new int[4];
        int player2moveDamage[] = new int[4];
        String player1PokemonName;
        String player2PokemonName;
        int moveUsed;
        float critChance = 6.25f;
    /**
     * Creates new form vsComputer
     */
    public vsComputer() {
        initComponents();
        
        config pokemon = new config();
        String pokemon_name = pokemon.pkmn_name;
        int pokemon_health = pokemon.pkmn_health;
        int pokemon_attack = pokemon.pkmn_attack;
        int pokemon_defense = pokemon.pkmn_defense;
        String pokemon_skill1 = pokemon.pkmn_skill1;
        int pokemon_skill1_damage = pokemon.pkmn_skill1DMG;
        String pokemon_skill2 = pokemon.pkmn_skill2;
        int pokemon_skill2_damage = pokemon.pkmn_skill2DMG;
        String pokemon_skill3 = pokemon.pkmn_skill3;
        int pokemon_skill3_damage = pokemon.pkmn_skill3DMG;
        String pokemon_skill4 = pokemon.pkmn_skill4;
        int pokemon_skill4_damage = pokemon.pkmn_skill4DMG;
        
        
        //My Pokemon
        player1(pokemon_name,pokemon_health,pokemon_attack,pokemon_defense,20);
        player1moveSet(pokemon_skill1,pokemon_skill2,pokemon_skill3,pokemon_skill4);
        player1moveDamage(pokemon_skill1_damage,pokemon_skill2_damage,pokemon_skill3_damage,pokemon_skill4_damage);
        p1PokemonName.setText(player1PokemonName);
        Health.setText(Integer.toString(player1Info[0]));
        p1PokemonHealth.setMaximum(player1Info[0]);
        p1PokemonHealth.setValue(player1Info[0]);
        //Enemy Pokemon
        player2("Marwan",200,100,100);
        player2moveSet("Libog","Manyak","dila","EUT");
        player2moveDamage(100,200,300,400);
        p2PokemonName.setText(player2PokemonName);
        enemyHealth.setText(Integer.toString(player2Info[0]));
        p2PokemonHealth.setMaximum(player2Info[0]);
        p2PokemonHealth.setValue(player2Info[0]);
        
        player1upperText.setText("What will "+player1Info[0]+" do?");
        
        p1PokemonHealthMax.setText("/ "+Integer.toString(player1Info[0]));
        p2PokemonHealthMax.setText("/ "+Integer.toString(player2Info[0]));
        player1Turn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        player1btn1 = new javax.swing.JButton();
        player1btn2 = new javax.swing.JButton();
        player1btn3 = new javax.swing.JButton();
        player1btn4 = new javax.swing.JButton();
        player1upperText = new javax.swing.JLabel();
        player1lowerText = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        player2upperText = new javax.swing.JLabel();
        player2lowerText = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        p2PokemonName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        p2PokemonHealth = new javax.swing.JProgressBar();
        p2PokemonHealthMax = new javax.swing.JLabel();
        enemyHealth = new javax.swing.JLabel();
        player2status = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        p1PokemonName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p1PokemonHealth = new javax.swing.JProgressBar();
        p1PokemonHealthMax = new javax.swing.JLabel();
        Health = new javax.swing.JLabel();
        player1status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pokemon Battle Simulator (vs. Computer)");

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jPanel15.setBackground(new java.awt.Color(204, 204, 0));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBackground(new java.awt.Color(0, 102, 153));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        player1btn1.setBackground(new java.awt.Color(255, 255, 255));
        player1btn1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player1btn1.setText("FIGHT");
        player1btn1.setBorder(null);
        player1btn1.setFocusPainted(false);
        player1btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1btn1ActionPerformed(evt);
            }
        });

        player1btn2.setBackground(new java.awt.Color(255, 255, 255));
        player1btn2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player1btn2.setText("BAG");
        player1btn2.setBorder(null);
        player1btn2.setFocusPainted(false);
        player1btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1btn2ActionPerformed(evt);
            }
        });

        player1btn3.setBackground(new java.awt.Color(255, 255, 255));
        player1btn3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player1btn3.setText("POKEMON");
        player1btn3.setBorder(null);
        player1btn3.setFocusPainted(false);
        player1btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1btn3ActionPerformed(evt);
            }
        });

        player1btn4.setBackground(new java.awt.Color(255, 255, 255));
        player1btn4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player1btn4.setText("RUN");
        player1btn4.setBorder(null);
        player1btn4.setFocusPainted(false);
        player1btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1btn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(player1btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(player1btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(player1btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1btn1)
                    .addComponent(player1btn2))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1btn3)
                    .addComponent(player1btn4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        player1upperText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        player1upperText.setForeground(new java.awt.Color(255, 255, 255));

        player1lowerText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player1lowerText.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player1upperText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(player1lowerText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(player1upperText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(player1lowerText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel19.setBackground(new java.awt.Color(204, 204, 0));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jPanel21.setBackground(new java.awt.Color(0, 102, 153));

        player2upperText.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        player2upperText.setForeground(new java.awt.Color(255, 255, 255));

        player2lowerText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        player2lowerText.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player2upperText, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addComponent(player2lowerText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(289, 289, 289))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(player2upperText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(player2lowerText, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        jPanel23.setBackground(new java.awt.Color(255, 255, 204));

        p2PokemonName.setText("Name");

        jLabel1.setText("HP");

        p2PokemonHealthMax.setText("/ 100");

        enemyHealth.setText("0");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(player2status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enemyHealth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2PokemonHealthMax)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(p2PokemonHealth, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                            .addComponent(p2PokemonName))
                        .addContainerGap())))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2PokemonName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(p2PokemonHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p2PokemonHealthMax)
                        .addComponent(enemyHealth))
                    .addComponent(player2status))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        jPanel24.setBackground(new java.awt.Color(255, 255, 204));

        p1PokemonName.setText("Name");

        jLabel3.setText("HP");

        p1PokemonHealthMax.setText("/ 100");

        Health.setText("0");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addComponent(player1status)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Health)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p1PokemonHealthMax)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(p1PokemonHealth, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                            .addComponent(p1PokemonName))
                        .addContainerGap())))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1PokemonName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(p1PokemonHealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(p1PokemonHealthMax)
                        .addComponent(Health))
                    .addComponent(player1status))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void player1damageCalculation(){
        Random critChance = new Random();
        int critRate=critChance.nextInt(100);
        int totalDamage = ((2*player1Info[3])/5+2)*(player1moveDamage[moveUsed]*(player1Info[1]/player2Info[2]))/50+2;
        int critDamage = totalDamage*2;
        if(critRate <= 10){
            player2Info[0]-=critDamage;
            player1lowerText.setText("Critical Hit! "+player2PokemonName+" takes "+critDamage+" damage.");
        }else{  
            player2Info[0]-=totalDamage;
            player1lowerText.setText(player2PokemonName+" takes "+totalDamage+" damage.");
        }
            enemyHealth.setText(Integer.toString(player2Info[0]));
            player1upperText.setText(player1PokemonName+" uses "+player1moveList[moveUsed]);
     
        p1PokemonHealth.setValue(player1Info[0]);
        p2PokemonHealth.setValue(player2Info[0]);
        
        player2Turn();
    }
    public void player2damageCalculation(){
        Random critChance = new Random();
        int critRate=critChance.nextInt(100);
        int totalDamage = ((2*player1Info[3])/5+2)*(player1moveDamage[moveUsed]*(player1Info[1]/player2Info[2]))/50+2;
        int critDamage = totalDamage*2;
        if(critRate <= 10){
            player1Info[0]-=critDamage;
            player2lowerText.setText("Critical Hit! "+player1PokemonName+" takes "+critDamage+" damage.");
        }else{
            player1Info[0]-=totalDamage;
            player2lowerText.setText(player1PokemonName+" takes "+totalDamage+" damage.");
        }
            Health.setText(Integer.toString(player1Info[0]));
            player2upperText.setText(player2PokemonName+" uses "+player2moveList[moveUsed]);
            
        
        p1PokemonHealth.setValue(player1Info[0]);
        p2PokemonHealth.setValue(player2Info[0]);
        
        player1Turn();
    }

    public void player1Turn(){        
        
        if(player1Info[0] <= 0){
            player1upperText.setText(player1PokemonName+" fainted.");
            player1lowerText.setText("You Lose");
            player2upperText.setText(player1PokemonName+" fainted.");
            player2lowerText.setText("You win!");
            player1status.setText("Lose");
            player2status.setText("Win");
            player1btn1.setEnabled(false);
            player1btn2.setEnabled(false);
            player1btn3.setEnabled(false);
            player1btn4.setEnabled(false);
            Health.setText("0");
            
        }else if(player2Info[0] <= 0){
            player1upperText.setText(player2PokemonName+" fainted.");
            player1lowerText.setText("You win!");
            player2upperText.setText(player2PokemonName+" fainted.");
            player2lowerText.setText("You lose!");
            player1status.setText("Win");
            player2status.setText("Lose");
            player1btn1.setEnabled(false);
            player1btn2.setEnabled(false);
            player1btn3.setEnabled(false);
            player1btn4.setEnabled(false);
            enemyHealth.setText("0");
        }else{            
            player1btn1.setText("FIGHT");
            player1btn2.setText("BAG");
            player1btn3.setText("POKEMON");
            player1btn4.setText("RUN");
        player1btn1.setEnabled(true);
        player1btn2.setEnabled(true);
        player1btn3.setEnabled(true);
        player1btn4.setEnabled(true);
        player1status.setText("Thinking ...");
        player2status.setText("Waiting ...");
        player1upperText.setText("What will "+player1PokemonName+" do?");
        player1lowerText.setText("");
        }
    }
    public void player2Turn(){        
        if(player1Info[0] <= 0){
            player1upperText.setText(player1PokemonName+" fainted.");
            player1lowerText.setText("You Lose");
            player2upperText.setText(player1PokemonName+" fainted.");
            player2lowerText.setText("You win!");
            player1status.setText("Lose");
            player2status.setText("Win");
            player1btn1.setEnabled(false);
            player1btn2.setEnabled(false);
            player1btn3.setEnabled(false);
            player1btn4.setEnabled(false);
            Health.setText("0");
        }else if(player2Info[0] <= 0){
            player1upperText.setText(player2PokemonName+" fainted.");
            player1lowerText.setText("You win!");
            player2upperText.setText(player2PokemonName+" fainted.");
            player2lowerText.setText("You lose!");
            player1status.setText("Win");
            player2status.setText("Lose");
            enemyHealth.setText("0");
        }else{            
        player1btn1.setEnabled(false);
        player1btn2.setEnabled(false);
        player1btn3.setEnabled(false);
        player1btn4.setEnabled(false);
        player2status.setText("Thinking ...");
        player1status.setText("Waiting ...");
        player2upperText.setText("What will "+player2PokemonName+" do?");
        player2lowerText.setText("");
        

        
        Random r = new Random();
        int randomMove=r.nextInt(player2moveList.length);
        moveUsed = randomMove;
            player2damageCalculation();
        }
    }
    
    private void player1btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1btn1ActionPerformed

            if(player1btn1.getText() == "FIGHT"){
            player1btn1.setText(player1moveList[0]);
            player1btn2.setText(player1moveList[1]);
            player1btn3.setText(player1moveList[2]);
            player1btn4.setText(player1moveList[3]);
            player1upperText.setText("Choose a skill.");
            player1lowerText.setText("");
        }else{
            moveUsed = 0;
            player1damageCalculation();
        }
    }//GEN-LAST:event_player1btn1ActionPerformed

    private void player1btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1btn2ActionPerformed
        if(player1btn2.getText() == "BAG"){
            player1upperText.setText("Your bag is empty.");
            player1lowerText.setText("");
        }else{
            moveUsed = 1;
            player1damageCalculation();
        }
    }//GEN-LAST:event_player1btn2ActionPerformed

    private void player1btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1btn3ActionPerformed
        if(player1btn3.getText() == "POKEMON"){
        }else{
            moveUsed = 2;
            player1damageCalculation();
        }
    }//GEN-LAST:event_player1btn3ActionPerformed

    private void player1btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1btn4ActionPerformed
        if(player1btn4.getText() == "RUN"){
            int input = JOptionPane.showConfirmDialog(null,
                "Are you sure?", "Player 1",JOptionPane.YES_NO_OPTION);
            if(input == 0){
                Home home = new Home();
                home.setVisible(true);
                this.setVisible(false);
            }
        }else{
            moveUsed = 3;
            player1damageCalculation();
        }
    }//GEN-LAST:event_player1btn4ActionPerformed

    public void player2(String name, int hp, int att, int def){
        player2PokemonName = name;    
        player2Info[0] = hp;
        player2Info[1] = att;
        player2Info[2] = def;  
    }
    public void player2moveSet(String a, String b, String c, String d){
        player2moveList[0] = a;
        player2moveList[1] = b;
        player2moveList[2] = c;
        player2moveList[3] = d;
    }
    public void player2moveDamage(int a, int b, int c, int d){
        player2moveDamage[0] = a;
        player2moveDamage[1] = b;
        player2moveDamage[2] = c;
        player2moveDamage[3] = d;
    }
    public void player1moveSet(String a, String b, String c, String d){
        player1moveList[0] = a;
        player1moveList[1] = b;
        player1moveList[2] = c;
        player1moveList[3] = d;
    }
    public void player1moveDamage(int a, int b, int c, int d){
        player1moveDamage[0] = a;
        player1moveDamage[1] = b;
        player1moveDamage[2] = c;
        player1moveDamage[3] = d;
    }
    public void player1(String name, int hp, int att, int def, int lv){
        player1PokemonName = name;    
        player1Info[0] = hp;
        player1Info[1] = att;
        player1Info[2] = def;
        player1Info[3] = lv;  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vsComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vsComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vsComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vsComputer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vsComputer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Health;
    private javax.swing.JLabel enemyHealth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JProgressBar p1PokemonHealth;
    private javax.swing.JLabel p1PokemonHealthMax;
    private javax.swing.JLabel p1PokemonName;
    private javax.swing.JProgressBar p2PokemonHealth;
    private javax.swing.JLabel p2PokemonHealthMax;
    private javax.swing.JLabel p2PokemonName;
    private javax.swing.JButton player1btn1;
    private javax.swing.JButton player1btn2;
    private javax.swing.JButton player1btn3;
    private javax.swing.JButton player1btn4;
    private javax.swing.JLabel player1lowerText;
    private javax.swing.JLabel player1status;
    private javax.swing.JLabel player1upperText;
    private javax.swing.JLabel player2lowerText;
    private javax.swing.JLabel player2status;
    private javax.swing.JLabel player2upperText;
    // End of variables declaration//GEN-END:variables
}
